// playground/react-ts/src/main.tsx
import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import './index.css';

ReactDOM.createRoot(
  (() => {
    const app = document.createElement('div');
    document.body.append(app);
    return app;
  })(),
).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
);

// playground/test-unocss/src/main.tsx
import { render, Portal } from 'solid-js/web';
import style from 'unocss?style';
import App from './App';

render(
  () => (
    <Portal useShadow>
      <App />
      {style}
    </Portal>
  ),
  (() => {
    const div = document.createElement('div');
    document.body.append(div);
    return div;
  })(),
);
